Rwd
korczas/styling pull request #2
Opened 2019-08-26 19:34 UTC by korczas

2019-08-27 07:57 UTC, ArekJanik requested changes

2019-08-27 07:57 UTC, ArekJanik commented on src/App.js
>      <div className="App">
`<>` will do

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/images/logo.svg
> +<?xml version="1.0" encoding="UTF-8"?>
svgomg

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/images/menu.svg
> +<!-- Generated by IcoMoon.io -->
Here the difference would not be as great as with the previous file, but still it's worth to remember about compression

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +  0%
Pretty cool :) One thing to improve it even further would be to use `scale` instead of `height/width`

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    box-shadow: 0 0px 10px 10px rgba($color-gray-dark, .3)
`0px` :triggered:

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    background: linear-gradient(to right, $color-gray-lightest, $color-white)
`background-image`

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      align-self: center
Already declared on :69

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      align-self: center
Already declared on :69

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    & > img
use BEM

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      width: 280px
Don't add a custom width for each breakpoint, just set the both columns (for image and text) with sth like `flex: 1`

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    & .play-button
use BEM

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      & img
you know what :)

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    font-size: $font-size-lg * 2
`$font-size-xl` is not used anywhere so feel free to do so :)

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    color: black
var

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      padding: $m-xxl * 3 0
Up to you, but for readability I tend to write it as `($m-xxl * 3) 0`

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +        transform: translateY(-50%)
`align-items: center` on parent would be simpler

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      width: 1000px
The breakpoint starts at 992px and you force a width of 1000px, which means that the horizontal scrollbar will appear. You can drop that and just add a `max-width: 1200px`

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +      width: 1200px
Is your IDE configured for adding an empty line at the end of file?

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/button.sass
> +      +animate(background-color)
Hard to explain in writing why this is wrong, will do in person just remind me 😁

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/navbar.sass
> +  background: linear-gradient(to right, $color-gray-lightest, $color-white)
`background-image` again. Do you know why? :)

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/navbar.sass
> +    display: flex
Why?

2019-08-27 07:57 UTC, ArekJanik commented on src/components/Navbar.js
> +      <div>
✂️

2019-08-27 07:57 UTC, ArekJanik commented on src/components/Navbar.js
> +import logo from "../assets/images/logo.svg";
https://create-react-app.dev/docs/adding-images-fonts-and-files#adding-svgs

2019-08-27 07:57 UTC, ArekJanik commented on src/components/Navbar.js
> +            onClick={() => toggleMenu(isMenuOpen => !isMenuOpen)}
`onClick` does not belong on any element other than `button`

2019-08-27 07:57 UTC, ArekJanik commented on src/components/Navbar.js
> +          <Button text="LOG IN" appearance="-secondary navbar__element" />
The uppercase should be handled by CSS

2019-08-27 07:57 UTC, ArekJanik commented on src/components/Navbar.js
> +        <div className={`navbar__elements ${isMenuOpen ? '' : '-hide'}`}>
Not only here but general remark - use semantic tags

2019-08-27 07:57 UTC, ArekJanik commented on src/assets/stylesheets/components/navbar.sass
>      min-height: $m-base * 3
remember about ordering

2019-08-27 07:57 UTC, ArekJanik commented on src/components/BusinessCommunication.js
> +          <span className="buscom__header">
Header as a span, with a `display: block` set in styles. Why is this wrong?

2019-08-27 07:57 UTC, ArekJanik commented on src/components/BusinessCommunication.js
> +    <div className="buscom__wrapper">
Just `buscom` is fine, no need for the wrapper

2019-08-27 07:57 UTC, ArekJanik commented on src/components/BusinessCommunication.js
> +            <Button text="Get Started" appearance="-success navbar__element" />
Not really a `navbar__element`

2019-08-27 19:40 UTC, korczas commented on src/assets/stylesheets/components/businessCommunication.sass
> +      width: 1200px
only in js files :/

2019-08-27 19:41 UTC, korczas commented on src/assets/stylesheets/components/navbar.sass
> +  background: linear-gradient(to right, $color-gray-lightest, $color-white)
yes, I know ;)

2019-08-27 19:42 UTC, korczas commented on src/assets/stylesheets/components/navbar.sass
> +    display: flex
error

2019-08-27 19:50 UTC, korczas commented on src/components/Navbar.js
> +import logo from "../assets/images/logo.svg";
nice! didn't know that

2019-08-28 06:27 UTC, ArekJanik requested changes
LMK when you apply the feedback, not just read it

2019-08-28 06:27 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    & > img
This is not a fix

2019-08-28 06:27 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
>    &__wrapper
The `__wrapper` is not needed, `buscom` is your main element. The way you wrote it, it suggests that `buscom__wrapper` sits somewhere inside `buscom`

2019-08-28 06:27 UTC, ArekJanik commented on src/assets/stylesheets/components/businessCommunication.sass
> +    background: linear-gradient(to right, $color-gray-lightest, $color-white)
Clicking `resolve` does not fix your code automatically :trollface:

2022-08-06 19:29 UTC, merged